/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 card-compressed.glb --transform 
Files: card-compressed.glb [530.18KB] > /mnt/z/axis/episode/axis/public/assets/3d/card-compressed-transformed.glb [507.37KB] (4%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/card-compressed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.293, -1.618, -0.67]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Text001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/card-compressed-transformed.glb')
