/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 card-compressed.glb --transform 
Files: card-compressed.glb [2.19MB] > /mnt/z/spectra/episode/spectrart/public/assets/3d/card-compressed-transformed.glb [523.94KB] (76%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/card-compressed-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Text001" position={[-0.293, -1.618, -0.67]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Text001_1" geometry={nodes.Text001_1.geometry} material={materials['Material.001']} />
          <mesh name="Text001_2" geometry={nodes.Text001_2.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-0.254, 0.731, -2.03]} scale={[5.423, 7.98, 0.825]} />
      </group>
    </group>
  )
}

useGLTF.preload('/card-compressed-transformed.glb')
